// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;
#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("Enseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("Project.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time(6)");

                    b.Property<int>("Jour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("EnseignantId");

                    b.HasIndex("GroupeId");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("Project.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("Project.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SurveillantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveillantId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("Project.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateNote")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<string>("TypeEvaluation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Project.Models.Surveillant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Surveillants");
                });

            modelBuilder.Entity("Project.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PendingRole")
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ecole.com",
                            IsApproved = true,
                            MotDePasseHash = "admin123",
                            Nom = "Système",
                            NomUtilisateur = "admin",
                            PendingRole = "Admin",
                            Prenom = "Administrateur",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Cours", b =>
                {
                    b.HasOne("Enseignant", "Enseignant")
                        .WithMany("Cours")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("Enseignant", b =>
                {
                    b.HasOne("Project.Models.Utilisateur", "Utilisateur")
                        .WithOne("EnseignantProfil")
                        .HasForeignKey("Enseignant", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Project.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("Cours", "Cours")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Groupe", "Groupe")
                        .WithMany("SessionsEmploiDuTemps")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Enseignant");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("Project.Models.Etudiant", b =>
                {
                    b.HasOne("Project.Models.Groupe", "Groupe")
                        .WithMany("Etudiants")
                        .HasForeignKey("GroupeId");

                    b.HasOne("Project.Models.Utilisateur", "Utilisateur")
                        .WithOne("EtudiantProfil")
                        .HasForeignKey("Project.Models.Etudiant", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Project.Models.Groupe", b =>
                {
                    b.HasOne("Project.Models.Surveillant", "Surveillant")
                        .WithMany("Groupes")
                        .HasForeignKey("SurveillantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Surveillant");
                });

            modelBuilder.Entity("Project.Models.Note", b =>
                {
                    b.HasOne("Cours", "Cours")
                        .WithMany("Notes")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Etudiant", "Etudiant")
                        .WithMany("Notes")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("Project.Models.Surveillant", b =>
                {
                    b.HasOne("Project.Models.Utilisateur", "Utilisateur")
                        .WithOne("SurveillantProfil")
                        .HasForeignKey("Project.Models.Surveillant", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Cours", b =>
                {
                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Enseignant", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("Project.Models.Etudiant", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Project.Models.Groupe", b =>
                {
                    b.Navigation("Etudiants");

                    b.Navigation("SessionsEmploiDuTemps");
                });

            modelBuilder.Entity("Project.Models.Surveillant", b =>
                {
                    b.Navigation("Groupes");
                });

            modelBuilder.Entity("Project.Models.Utilisateur", b =>
                {
                    b.Navigation("EnseignantProfil")
                        .IsRequired();

                    b.Navigation("EtudiantProfil")
                        .IsRequired();

                    b.Navigation("SurveillantProfil")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
